module.exports = {
    extends: [
        'eslint-config-airbnb/rules/react'
    ],

    plugins: [
        
    ],

    rules: {
        'comma-dangle': [2, 'always-multiline'],
        'max-len': [2, 160, 4, { 'ignorePattern': 'data:image/' }],
        'no-cond-assign': [2, 'except-parens'],
        'no-constant-condition': 2,
        'no-control-regex': 2,
        'no-debugger': 2,
        'no-dupe-args': 2,
        'no-dupe-keys': 2,
        'no-duplicate-case': 2,
        'no-empty': 2,
        'no-empty-character-class': 2,
        'no-ex-assign': 2,
        'no-extra-boolean-cast': 2,
        'no-extra-parens':  0,
        'no-extra-semi': 2,
        'no-func-assign': 2,
        'no-invalid-regexp': 2,
        'no-irregular-whitespace': 2,
        'no-negated-in-lhs': 2,
        'no-obj-calls': 2,
        'no-regex-spaces': 2,
        'no-sparse-arrays': 2,
        'no-unreachable': 2,
        'no-unexpected-multiline': 2,
        'use-isnan': 2,
        'valid-jsdoc': [2, {
            'prefer': {
                'return': 'returns',
            },
            'requireReturn': false,
            'requireReturnDescription': false
        }],
        'valid-typeof': 2,
        'wrap-iife': 2,

        'accessor-pairs': 2,
        'block-scoped-var': 0,
        'complexity': 0,
        'consistent-return': 0,
        'dot-location': [2, 'property'],
        'dot-notation': 2,
        'no-alert': 2,
        'no-div-regex': 2,
        'no-else-return': 2,
        'no-eval': 2,
        'no-extend-native': 2,
        'no-extra-bind': 2,
        'no-fallthrough': 2,
        'no-floating-decimal': 2,
        'no-implied-eval': 2,
        'no-invalid-this': 2,
        'no-labels': 2,
        'no-lone-blocks': 2,
        'no-loop-func': 2,
        'no-magic-numbers': [2, {
            'ignore': [-1, 0, 1, 2],
            'enforceConst': true
        }],
        'no-multi-spaces': 2,
        'no-multi-str': 2,
        'no-native-reassign': 2,
        'no-new-func': 2,
        'no-new-wrappers': 2,
        'no-new': 2,
        'no-octal-escape': 2,
        'no-octal': 2,
        'no-redeclare': 2,
        'no-return-assign': 2,
        'no-script-url': 2,
        'no-self-compare': 2,
        'no-sequences': 2,
        'no-throw-literal': 2,
        'no-unused-expressions': 2,
        'no-useless-call': 2,
        'no-useless-concat': 2,
        'no-void': 2,
        'no-warning-comments': 0,
        'no-with': 2,
        'radix': 0,
        'vars-on-top': 0,
        'yoda': 0,

        'init-declarations': 0,
        'no-catch-shadow': 2,
        'no-delete-var': 2,
        'no-label-var': 2,
        'no-shadow-restricted-names': 2,
        'no-shadow': 2,
        'no-undef-init': 2,
        'no-undef': 2,
        'no-undefined': 0,
        'no-unused-vars': [2, {'args': 'none'}],
        'no-use-before-define': [2, 'nofunc'],

        'array-bracket-spacing': [2, 'never'],
        'brace-style': 2,
        'camelcase': [2, {
            'properties': 'never'
        }],
        'comma-spacing': 2,
        'comma-style': [2, 'last'],
        'computed-property-spacing': [2, 'never'],
        'consistent-this': [2, 'self'],
        'eol-last': 2,
        'func-names': 0,
        'func-style': 0,
        'id-length': 0,
        'id-match': 0,
        'indent': [2, 4, {'SwitchCase': 1}],
        'key-spacing': 2,
        'keyword-spacing': 2,
        'linebreak-style': [2, 'unix'],
        'lines-around-comment': 2,
        "max-depth": [2,4],
        "max-len": [1, 300, 4],
        'max-nested-callbacks': [1, 3],
        'max-params': [1, 6],
        'max-statements': 0,
        'new-cap': [2, {
            'capIsNewExceptions': [
                '$.Callbacks',
                '$.Deferred',
                '$.Event'
            ]
        }],
        'new-parens': 2,
        'newline-after-var': 0,
        'no-array-constructor': 2,
        'no-bitwise': 0,
        'no-continue': 0,
        'no-inline-comments': 0,
        'no-lonely-if': 2,
        'no-mixed-spaces-and-tabs': 2,
        'no-multiple-empty-lines': 2,
        'no-negated-condition': 2,
        'no-nested-ternary': 2,
        'no-new-object': 2,
        'no-plusplus': 0,
        'no-restricted-syntax': 0,
        'no-spaced-func': 2,
        'no-ternary': 0,
        'object-curly-spacing': [2, 'always'],
        "one-var": [2, "never"],
        'operator-assignment': 0,
        'operator-linebreak': [2, 'after'],
        'padded-blocks': 0,
        'quote-props': [2, 'consistent-as-needed'],
        'quotes': [0, 'single', 'avoid-escape'],
        'require-jsdoc': 0,
        'semi-spacing': 2,
        'semi': 2,
        'sort-vars': 0,
        'space-before-blocks': [2, 'always'],
        'space-before-function-paren': [1, 'never'],
        'space-in-parens': 2,
        'space-infix-ops': 2,
        'space-unary-ops': 2,
        'spaced-comment': 0,
        'wrap-regex': 0,

        // ES6 rules
        'arrow-parens': [2, 'as-needed'],
        'no-const-assign': 2,
        'no-var': 2,
        'prefer-const': 2,
        'prefer-spread': 1,
        'prefer-template': 0,

        'jsx-quotes': [2, 'prefer-double'],
        'react/react-in-jsx-scope': 2,
        'react/jsx-indent-props': [2, 4],
        'react/jsx-no-bind': 0
    },

    env: {
        'browser': true,
        'es6': true,
        'node': true
    },

    parserOptions: {
      ecmaFeatures: {
        'jsx': true,
        'experimentalObjectRestSpread': true,
      },
      ecmaVersion: 6,
      sourceType: 'module',
    },

    ext: [
        '.js',
        '.jsx'
    ],

    globals: {
    }
}
